#!/usr/bin/env bash
# Idempotent repository bootstrap for the MojShop monorepo.
# Sets up PostgreSQL + the Next.js web app (in web/): installs deps, syncs the
# Prisma schema, and seeds local demo data.
set -euo pipefail

cd "$(dirname "$0")/.."
ROOT="$(pwd)"
WEB_DIR="$ROOT/web"

PG_MAJOR=16
DB_NAME=mojshop
DB_USER=mojshop
DB_PASS=mojshop

echo "==> Ensuring PostgreSQL ${PG_MAJOR} is installed"
if ! command -v pg_ctlcluster >/dev/null 2>&1; then
  sudo apt-get update
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y postgresql postgresql-contrib
fi

echo "==> Starting PostgreSQL cluster"
sudo pg_ctlcluster "${PG_MAJOR}" main start 2>/dev/null || true

# Wait for the server to accept connections.
for _ in $(seq 1 30); do
  if sudo -u postgres pg_isready -q; then break; fi
  sleep 1
done

echo "==> Provisioning database role and database"
sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='${DB_USER}'" | grep -q 1 \
  || sudo -u postgres psql -c "CREATE ROLE ${DB_USER} WITH LOGIN PASSWORD '${DB_PASS}' CREATEDB;"
sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='${DB_NAME}'" | grep -q 1 \
  || sudo -u postgres psql -c "CREATE DATABASE ${DB_NAME} OWNER ${DB_USER};"

echo "==> Ensuring web/.env exists"
if [ ! -f "$WEB_DIR/.env" ]; then
  cat > "$WEB_DIR/.env" <<EOF
# Local development environment (Cloud Agent) — generated by .cursor/install.sh
DATABASE_URL="postgresql://${DB_USER}:${DB_PASS}@127.0.0.1:5432/${DB_NAME}?schema=public"
NEXT_PUBLIC_APP_URL="http://localhost:3000"
ADMIN_PANEL_PASSWORD="Petrovaradin1!"

# Clerk auth keys are intentionally omitted so @clerk/nextjs runs in keyless
# development mode. Add real keys here to enable full auth:
# NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY="pk_test_..."
# CLERK_SECRET_KEY="sk_test_..."

# Optional integrations (not required for local MVP):
# UPLOADTHING_TOKEN=""
# NEXT_PUBLIC_UPLOADTHING_APP_ID=""
# RESEND_API_KEY=""
# FAL_KEY=""
EOF
fi

echo "==> Installing web dependencies"
cd "$WEB_DIR"
npm install

# NOTE: the committed Prisma migrations are out of sync with prisma/schema.prisma
# (they predate several schema columns), so we sync the schema directly with
# `prisma db push` instead of `prisma migrate deploy`.
echo "==> Syncing Prisma schema to the database"
npx prisma db push

echo "==> Seeding local demo data (Butik Mila)"
npm run db:seed

echo "==> Install complete (web). For the mobile app: cd mobile && npm install"
