-- KakoMiStoji: public buy links, shareable results and consumer analytics events.

ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "purchaseUrl" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "purchaseUrl" TEXT;
ALTER TABLE "TryOnJob" ADD COLUMN IF NOT EXISTS "shareToken" TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS "TryOnJob_shareToken_key" ON "TryOnJob"("shareToken");

ALTER TYPE "TryOnAnalyticsEventType" ADD VALUE IF NOT EXISTS 'KMS_LANDING_VIEW';
ALTER TYPE "TryOnAnalyticsEventType" ADD VALUE IF NOT EXISTS 'KMS_SHOP_VIEW';
ALTER TYPE "TryOnAnalyticsEventType" ADD VALUE IF NOT EXISTS 'KMS_PRODUCT_VIEW';
ALTER TYPE "TryOnAnalyticsEventType" ADD VALUE IF NOT EXISTS 'KMS_PHOTO_UPLOADED';
ALTER TYPE "TryOnAnalyticsEventType" ADD VALUE IF NOT EXISTS 'KMS_CONSENT_GIVEN';
ALTER TYPE "TryOnAnalyticsEventType" ADD VALUE IF NOT EXISTS 'KMS_SHARE_CLICKED';
ALTER TYPE "TryOnAnalyticsEventType" ADD VALUE IF NOT EXISTS 'KMS_BUY_CLICKED';
ALTER TYPE "TryOnAnalyticsEventType" ADD VALUE IF NOT EXISTS 'KMS_TRY_ANOTHER_CLICKED';
